version: "2.1"

services:
  php:
    image: denimsoft/php:7.2-zts-alpine
    working_dir: /opt/project
    ports:
      # ssh port
      - "127.0.0.1:${SSH_PORT:-2222}:22"
    volumes:
      # ssh keys
      - "$HOME/.ssh/id_rsa.pub:/home/$USER/.ssh/authorized_keys"
      - ssh:/etc/ssh
      # project
      - .:/opt/project

volumes:
    ssh:
